01/08/2026,"Skyler, forever at war with the black dog, had another black dog by the name of Patchy, who was a sunbeam in the darkness of her depression."
02/08/2026,"Sienna was forever waging a war against the term 'black dog' being used for depression. She'd had a few black dogs in her lifetime, and they were all the antithesis."
03/08/2026,"A man leans against a wall, stretching out his hamstrings, or propping up the brickwork. Kevin hopes it is the former."
04/08/2026,"On the days when his altruism hadn't turned up for work, train guard Ken was more inclined to close the door on sprinting passengers, even if they technically had thirty seconds to spare."
05/08/2026,"There would be no hanky panky for lanky Hank Shanky, until he forwent the use of hankies."
06/08/2026,"Though he'd never been interested in hair magazines before, Kerry was desperate for something to alleviate the boredom while waiting for the barber. He left having gained a new appreciation for the profession, and having lost an inch or so from his mop."
07/08/2026,"Gazza had opinions about Gaza which, considering his dinner-table audience, he wisely kept to himself."
08/08/2026,"Raquel was momentarily stuck for conversation topics when talking to a gaggle of bogans, but was saved when 'Have you guys ever been to Bali?' sprang to mind."
09/08/2026,"Momo the mastiff slept on his owner's silk bedsheets, ate the finest smoked salmon and was all-around treated like a queen, and yet she still went for the discarded roast chicken bag with the rabidity of an uncultured dog."
10/08/2026,"Quincey was typically mistaken for being a sensitive guy, and yet his teeth were the most sensitive part of him, as evidenced by his toothpaste."
11/08/2026,"Chris cut himself while shaving, but lucky for him, much of his blood flow was directed away from the cut and down to his penis, because his wife had just stepped out of the shower."
12/08/2026,"Chuck Mansfield outright failed the testosterone test. She was over the moon at the results; a major milestone in her transition to becoming a woman."
13/08/2026,"The bowling pins unionised and went on strike for better working conditions. Management kept pelting bowling balls at the picket line, but it wasn't anything they weren't used to, and they eventually negotiated a better deal."
14/08/2026,"A small girl stands on the back of her sister's pram, like an emperor on their chariot, riding around the Coliseum, cheers of adoration engulfing her."
15/08/2026,"'Lift full, building empty' was a modern Chinese proverb that Yu Jiaying lived by every time he finished work for the day."
16/08/2026,"The rapidly-pacing, few-beers-short-of-a-six-pack bloke would have certainly blown past his ten thousand daily steps, if he'd had the mental capacity to acknowledge it."
17/08/2026,"It might have been the greatest recipes ever recorded, but it was hard to find under the fifty metres of unapologetic, unrelated drivel on the website."
18/08/2026,"While doing his morning stretches on his yoga mat, it struck Henry Doevill halfway through child's pose that if he were Muslim, he could probably kill two birds with one stone and get in his morning prayer too."
19/08/2026,"Tilly was always trying to keep up with her friends on their electric bikes. She later credited the forever-chasing to her dominance in the peloton."
20/08/2026,"Monica almost didn't want to resolve her billing issue with the phone company. Their hold music was excellent."
21/08/2026,"Giselle always went to the furthest supermarket away from her house. By the time she'd inevitably realised she'd forgotten an item, she was pulling level with the supermarket closest to her house. Plus, it kept her step count up."
22/08/2026,"Aiden's preference for neater whiskey increased as he himself got progressively more sloppy."
23/08/2026,"There was not a lot of give, if any, in Christian's white linen shirt. It was like his nipples were pressed up against a semi-transparent pane of glass."
24/08/2026,"Shucked of bark, the light-grey gumtree welcomed summer, and even the shedding dog that paused for a moment on its walk to raise its leg and piss on the base of the tree."
25/08/2026,"Milo hoarded the instruction booklets for his appliances like wasn't just going to figure out how they worked with trial and error, like he always did."
26/08/2026,"Kyle watched as his older brother passed over the money so that he got his milkshake. He saw his brother's hands wrap around his own drink, and wondered if they were the keys to the kingdom."
27/08/2026,"Though her bones creaked, and she needed to colour her hair again, Rachel was comforted in the fact that there was indeed life after thirty."
28/08/2026,"Crickets. All Tiana could hear after her powerful oratory were crickets. After all, she was practising her rousing speech on a solo bushwalk."
29/08/2026,"Much like her ex, who lived locally, Milly extended her perfected path deviation when it came to the physio she'd dropped for someone else."
30/08/2026,"The two shirtless runners on the esplanade almost ran into each other - their perfect, perky pecs practically poking."
31/08/2026,"Jeremy Champion, child, demolished just the icing off the top of his finger-bun. He was disappointed when his mother instructed him to eat the now sugarless bread, too."
01/09/2026,"The tattered remnants of a rainbow hung in the air, like God had dragged a near-empty pen through the sky."
02/09/2026,"It broke Yasmin's heart, one cold morning on the train, where she found herself looking at the phone of the person in the seat in front of her, as the stranger typed into Google: 'How long does an 85 year old man with lung cancer which has spread to the lymph nodes have to live?'"
03/09/2026,"Gordon was a high-maintenance maintenance man. He would dissolve into doubt about the quality of his work unless he was given constant reassurance."
04/09/2026,"Though the crowd was not there for him, to Segway camera operator Matt Riebald, the stadium was his Coliseum, the Segway his chariot."
05/09/2026,"Donald was a grunter at the gym, but surprisingly quiet during love-making."
06/09/2026,"It was a van-life mind-slip. Ronda had forgotten to take a knife with her. Luckily, she prised a surfboard fin from her board and used that instead."
07/09/2026,"Barista Bobby Barrass practised gratitude by default at his job, calling out customer's names, preceded by 'Thanks', when their coffees was ready."
08/09/2026,"It wasn't the fact his KKK uniform had gone through the wash and come out pink that finally made Wayne renounce the order, but it sure helped."
09/09/2026,"Tamara's coffee order was roughly the same length as a short story."
10/09/2026,"Brian Kennedy smirked derisively at the phone-addicted individuals on his bus, taking a moment to bask in his superiority. He decided to reward himself with a scroll on Instagram."
11/09/2026,"Though Sargeant Indi Hawkins died of exposure, thanks to her insistence on wearing her Burberry trench coat to the trenches that scarred the front lines, she sure as shit looked good doing it."
12/09/2026,"Buzz had done it backwards. He started out as young and boring and ended up old and exciting."
13/09/2026,"The ageing shark didn't attack long-time ocean swimmer Frankie Freestyle, though it did provide enough of a fright to trigger the heart attack and drowning combo that did. But before Frankie saw the shark, gliding along in the gloom, they were just a couple of old blokes, enjoying a swim."
14/09/2026,"Thanks to his fat, porky fingers, Raymond was inundated with results for 'pork' instead of 'porn.'"
15/09/2026,"Amanda blamed Steve Jobs for the proliferation of the conference-cum-rock-concert, as she stifled the cringe she felt from the industry standards convention."
16/09/2026,"It didn't know it yet, but the pristine white hotel towel was about to cop a beating from the face of a woman who'd forgotten her makeup wipes."
17/09/2026,"After the whitewash, the cricketing whites were thrown sulkily into the white wash."
18/09/2026,"Andre arrived at the housewarming, and immediately realised he'd misread the invitation. He left his potato cannon at the front door; there would be no housewarring."
19/09/2026,"The group of non-sports watchers at the party were all giddily drunk, and entertained themselves by watching two bored boyfriends in a corner watching the footy together on a phone. This proxy sports spectatorship actually became a great icebreaker, and they all ended up having a great night."
20/09/2026,"Hector had to chuckle. After years of throwing people under the bus for various things, he was now being held by four of his most aggrieved victims, about to throw him under the 977 bus."
21/09/2026,"Though her weak immune system wasn't the cause of her getting into a car accident, Mary did get a bit rundown in the hospital as she was recovering after being run over."
22/09/2026,"Fran enjoyed letting his mind wander, but was always wary of it getting too far away. In a way, he kept it on one of those long retractable dog leads."
23/09/2026,"Amateur psychologist Rina was proud of her ability to diagnose conditions at a hundred paces. For example, she was certain that the gunslinger standing across from her in the empty Main Street of frontier town, hand hovering above his gun, had anger management problems."
24/09/2026,"Jane's dog Milly wandered through the twilight grass, carving her way through a kaleidoscope of scents; she let her own mind wander alongside Milly's snout, and then rise above and high into the early-evening sky."
25/09/2026,"Successive days on the bags had Martin noticing, for the first time, the presence of bags under his eyes."
26/09/2026,"Going against the grain, frontman Dave Dior demanded from the crowd the largest cheers for his bandmates, and the smallest for himself."
27/09/2026,"A group of modern-day sages clustered around a small cafe table. 'It is what it is,' said the one with the flat white, to close out their story. 'It is what it is,' confirmed the one with the espresso. 'It is,' said the mocha. It really was what it was."
28/09/2026,"The trash produced at the white-trash wedding was the furthest thing from white possible."
29/09/2026,"The stroke was doubly painful for Barbara. The stroke itself was no picnic, obviously, but she abhorred the smell of burnt toast too."
30/09/2026,"The ten-kilo bag of basmati rice wasn't going to fit on the small shelf next to the register, where other people had dumped random items they were no longer interested in purchasing. Jack would have to heft that bad-boy back to where he found it."