01/04/2023,"Lionel was hedging his post-death bets by signing up to all the major religions beforehand. Plus some minor ones, just to be safe."
02/04/2023,"The scam artist was more of an apprentice, though he aspired to greater heights."
03/04/2023,"Lazy Susan couldn't be arsed going to the Chinese restaurant for dinner; she had it delivered instead."
04/04/2023,"Once again, hairdresser Mabel withheld her professional opinion from her client, who was holding onto the very last remnants of his hair."
05/04/2023,"A mini-rainbow danced on Heidi's fingers as she sat writing at her desk in the early afternoon sun."
06/04/2023,"A tired child grasps a sign in the middle of a protest, though not the reason behind the marching, the chanting, the screaming. "
07/04/2023,"The two old friends knew they were back when their emphysemic laughs synched up at the pub."
08/04/2023,"As the ball went up for the first game of the year, the armchair expert adjusted his arse, burped, and prepared his epithets."
09/04/2023,"An empty longneck stands under a park bench, a bookmark of the distant weekend."
10/04/2023,"A solitary student battles her way through a reference tome as those around her scroll on laptops and phones."
11/04/2023,"They crowded the kebab caravan, spraying the air with 'Thanks bruvva,' 'Extra sauce please bruvva' and 'Love you bruvva.'"
12/04/2023,"Despite his mug's message, Doug was neither calm and only just managing to carry on."
13/04/2023,"As the rain lashed the windows, Casey once again thanked her lucky stars she worked in an office."
14/04/2023,"'Segregation is critical,' said the CEO, before quickly tacking on, 'in the waste management industry.'"
15/04/2023,"It was warm in the meeting room. The big-lunch eater and new father had no chance of staying awake."
16/04/2023,"Tilly's work drawer was a cornucopia of free swag from conferences over the years, which she flogged to her nieces and nephews whenever she couldn't be bothered buying them a gift for their birthdays."
17/04/2023,"Brent triple-checked his camera was off before beginning a good nose-pick during the laborious meeting."
18/04/2023,"From his airplane window, James could see the ground crew throw his bag like it weighed nothing. He winced for anything fragile inside of it."
19/04/2023,"The flight attendants prepared for another safety demonstration that would be promptly ignored by close to 200 people."
20/04/2023,"Dazed, post-massage Claire came close to face-planting into her bowl of pho."
21/04/2023,"It was like something out of a poor anthropological documentary, the poor woman trying to get through airport security with any semblance of grace and ease."
22/04/2023,"The youngest of the family flicked and flitted around the cityscape of his elder siblings and parents, bored out of his brain."
23/04/2023,"The dog didn’t mind being left out the front of the supermarket. It was pats aplenty and a thousand new scents to sniff."
24/04/2023,"The heart surgeon, not so adept at understanding metaphors, disagreed with the idea that beauty was on the inside."
25/04/2023,"Thanks to its most recent software update, Mark found his Tesla attempting to run the worst fuel-guzzlers off the road when on Autopilot mode."
26/04/2023,"Corporate drone Shane flicked to holiday mode as soon as the scent of marijuana hit him coming into the bohemian beachside suburb."
27/04/2023,"Marie’s daughter nuzzled into her neck at the end of the long day, washing away all of Marie’s stress and annoyance she had been the very source of in the first place."
28/04/2023,"Remnants of sandcastles stood like long lost ruins as the tides overran them."
29/04/2023,"The group of fathers paused at the pub and peered through the bottom of their bifocal lenses as they tapped out texts to their wives with a single finger."
30/04/2023,"Having already woken up on the wrong side of the bed, Jannette climbed straight back in to spare the world of her grumpy state."