01/08/2023,"Alice collected shot glasses as mementos of her travels, which was indicative more of her alcoholism than it was her love of globetrotting."
02/08/2023,"On the whole, Sally found her move from an apartment to a house a chore. But at least there wasn't a downstairs neighbour to complain when the ABBA was pumping and the wine was flowing."
03/08/2023,"The rainbow lorikeets flitted around an open window, picking at a bunch of grapes in the fruit bowl."
04/08/2023,"Used and abused, the hairdryer in the bridal suite breathed a sigh of relief as the women left for the waiting limousines."
05/08/2023,"The person running the workshop had a hard time getting the participants to do some blue sky thinking, considering the depressive affect the rain clouds were having."
06/08/2023,"A pigeon lands on a busy road, before quickly flying out of the way of a speeding truck, and landing again in the same spot. To budding young scientist, Marcy, it had her thinking how to test whether pigeons have a form of Alzheimer's."
07/08/2023,"The credit card payment plan was a good idea, if not for Jodie's vehement opposition to paying the instalments, and her industriousness in changing her name and moving countries to escape the debt."
08/08/2023,"It was strange to be back at a music festival after all this time. Whereas Duncan had spent most of the last one off his face and moshing as hard as his body would allow it, this time he was content to raise his young, ear-plugged daughter onto his shoulders and bop in time to the music."
09/08/2023,"Sidney was a smart cookie, but God she loved a mind-numbing reality show."
10/08/2023,"Jimmy had spent a good hour digging the perfect sand chair, but failed to appreciate the waxing and waning of the tide, and soon woke up to lapping water."
11/08/2023,"It was seven o'clock at night, and the apartment hallway smelled like a blend of East meets West, North meets South."
12/08/2023,"Aisha was handy with electronics, so she gave her smoke detector an upgrade. It now played Johnny Cash's 'Ring of Fire' at full ball whenever she overdid her Sunday roast."
13/08/2023,"The playground game ended with a misstep, knobbly knees scraping asphalt, blubbering tears and a call to Mum from the sickbay."
14/08/2023,"Deacon had carved out a corner office after a blistering career, and often rewarded himself with a good nose pick. Though this nasal mining was hidden from his colleagues, it appeared in full view of the building next door."
15/08/2023,"The traffic cone atop the traffic lights offered mild amusement for the morning commuters, whose thoughts all turned from the inevitability of the work day to 'How the hell did that get up there?'"
16/08/2023,"His son's iPad spending spree didn't irk Miles because he blew $600, it was the fact all he bought were 42 Nicholas Cage pillowcases."
17/08/2023,"The blood bank celebrated Basil's 250th donation by gifting him and his family tickets to the latest Dracula movie."
18/08/2023,"Estelle was on her balcony when the apple fell past her. Quickly followed the roast pig. She immediately got up and went to buy a lottery ticket."
19/08/2023,"A man holds a book one-handed, the other trapped under his husband as he lies next to him, sleeping. When he has to change page, he uses a thin reed of air and a deft thumb."
20/08/2023,"An old pub stands at the top of a street lined with sweet gums, in the throes of autumn, leaves a kaleidoscope of colour. The pub's chimney seeps smoke; it makes for sweet drinking for rugged-up patrons on the tables outside."
21/08/2023,"A police helicopter thrums overhead, while the elderly mob in front of Parliament House protesting for the right to die raised gnarled middle fingers in response."
22/08/2023,"Carmen was setting a cracking pace on her run, but as soon as she rounded the corner of the Oslo Opera House, a gust of wind picked up her hat and tossed it into the bay. She dove straight in after it and began setting a cracking pace on her swim instead."
23/08/2023,"Lela turned a javelin Olympic bronze into a kebab shop empire. After a while, the fact she didn't win gold didn't irk her at all."
24/08/2023,"Pete's girlfriend was going to the beautician's for something called a 'cosmelan pigmentation treatment', which sounded better than the 'laser skin resurfacing', but nowhere near as sadistic as the 'dermapen skin needling.' He was surprised when she came back in one piece."
25/08/2023,"Lucy's television did not received a dinner plate to the screen well after the show she was watching left her one too many cliffhangers."
26/08/2023,"They were the office polar opposites. Nigel always forgot his laptop had a touch screen, while Cecilia couldn't work without one."
27/08/2023,"Clayton was a big fan of his browser's ad-blocker. He once tried to implement a similar ad-blocker in the physical world, but found it hard to navigate with a blindfold on and earplugs in."
28/08/2023,"The homeless slept undercover around the grand old courtroom. As the lawyers, clients and witnesses rolled through the metal detectors the next morning, the dishevelled men and women were ushered away; an eyesore too cheap to afford justice."
29/08/2023,"Mohammad didn't construct his underground bunker to stave off societal collapse, rather he was scared of heights, enjoyed solitude, hence his workaround from hiking up a mountain. "
30/08/2023,"As part of the transition away from fossil fuels, among the nuclear and renewable energy options, the government also decided to fund an experiment into giving people with ADD coffee and letting them loose on a hamster wheel to generate power."
31/08/2023,"Megan was offered a vegan sausage on a roll as she walked into a polling place, which set her vote firmly against the Greens and any other party with whom they shared similar ideologies."