name: Scheduled Job

on:
  schedule:
    - cron: "0 8 * * *" #AEDT
    # - cron: "0 9 * * *" #AEST

# on: push #on commit

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: "16"
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          IG_UAT: ${{ secrets.IG_UAT }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          M_INTEGRATION_TOKEN: ${{ secrets.M_INTEGRATION_TOKEN }}
          R_USERNAME: ${{ secrets.R_USERNAME }}
          R_PASSWORD: ${{ secrets.R_PASSWORD }}
          R_CLIENT: ${{ secrets.R_CLIENT }}
          R_SECRET: ${{ secrets.R_SECRET }}
          FB_PAT: ${{ secrets.FB_PAT }}
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          E_USERNAME: ${{ secrets.E_USERNAME }}
          E_PASSWORD: ${{ secrets.E_PASSWORD }}
        run: node post-scheduled.js "$TWITTER_CONSUMER_KEY" "$TWITTER_CONSUMER_SECRET" "$TWITTER_ACCESS_TOKEN_KEY" "$TWITTER_ACCESS_TOKEN_SECRET" "$IG_UAT" "$IG_USER_ID" "$M_INTEGRATION_TOKEN" "$R_USERNAME" "$R_PASSWORD" "$R_CLIENT" "$R_SECRET" "$FB_PAT" "$FB_PAGE_ID" "$E_USERNAME" "$E_PASSWORD"
