name: Scheduled Job

on: [push]

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - env: 
          SECRET: ${{ secrets.TEST }}
        run: node test.js "$SECRET"
        
